name: zeekay
favicon: null
layout_spectrum: 0.42540895589627326
typography_spectrum: 0.20442760572768748
title: zeekay
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28183c'
    - '#632d51'
    - '#af516b'
    - '#918248'
    - '#a447d6'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
